version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
      - "3000:3000"  # BrowserSync main port
      - "3001:3001"  # BrowserSync UI port
    volumes:
      - .:/var/www/html
    container_name: php_app
    environment:
      - BROWSER_SYNC_HOST=0.0.0.0
      - BROWSER_SYNC_PORT=3000
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: juegosrol
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

